### ISSUE TITLE
exit code on error is 0 instead of error code

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#204]
![image](https://user-images.githubusercontent.com/6539235/61214912-889c4e00-a709-11e9-8aad-92665f837f66.png)

**Comment by thepiwo** [comment]
@maptuhec @alekseytsekov did someone have a look at this?

**Comment by maptuhec** [comment]
@thepiwo  it looks like that the node is not started, atleast this is the error telling. If you can share more info how to reproduce we will investigate

**Comment by thepiwo** [comment]
It's not about the error, it is that the exit code 0 which stands for successful

**Comment by maptuhec** [comment]
oh my bad, we will check it and leave a proper message

**Comment by alekseytsekov** [comment]
isn't this exit code from 'forgae test' ? it is successfully executed, all tests are run. but test itself can be successful or unsuccessful and the exit code do not depends from tests?

**Comment by thepiwo** [comment]
The exit code is expected to be dependend on the tests, to make things like ci fail if the tests were not successful. I think this is common among testing frameworks

**Comment by thepiwo** [comment]
Closed as in done?

**Comment by alekseytsekov** [comment]
yes, it's done
![Screenshot 2019-10-11 at 10 13 35](https://user-images.githubusercontent.com/15261656/66928080-819f1780-f039-11e9-99da-edde740c5641.png)
