### ISSUE TITLE
add test as npm script 

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#214]

**Comment by maptuhec** [comment]
@thepiwo  With this issue do you mean, to add new npm script **test**, that will run all *.js* files from the **test** folder? If yes how is this different from the **aeproject test** command?

**Comment by thepiwo** [comment]
Yes, that's what I would expect. Its helpful as npm scripts are well integrated in many idea/editors and aeproject is not yet.

**Comment by maptuhec** [comment]
This issue is fixed in PR: 
https://github.com/aeternity/aepp-aeproject-js/pull/256#pullrequestreview-308445592
