### ISSUE TITLE
if port 3080 is used "node" wont work

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#231]
===== Node already started and healthy! =====

but no nodes are running

**Comment by maptuhec** [comment]
@thepiwo  Can you confirm that you got the successful message but still the nodes were actually not running ?

**Comment by thepiwo** [comment]
Yes, I did encounter this issue multiple times a day when developing, as in some setups I use my own compiler/node and in some the forgae nodes. 

This is also a problem with multiple forgae setups on the same machine.
