### ISSUE TITLE
aeproject node runs forever without error if behind firewall that forbids docker pull

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#269]

**Comment by thepiwo** [comment]
how is this resolved?

**Comment by alekseytsekov** [comment]
Hi @thepiwo 
There was an error that was not handled properly, and the process did not stop. Now when error occurs, we terminate the process and show the error message. Tested on Linux, Mac and Windows.

**Comment by maptuhec** [comment]
Also, a disclaimer for using firewalls was added to the documentation, so the users should grant some permissions to the docker.
