### ISSUE TITLE
aeproject compile fails if sophia standard library is used

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#272]
https://forum.aeternity.com/t/how-to-iterate-over-a-list-in-sophia/5236/7

**Comment by maptuhec** [comment]
https://forum.aeternity.com/t/how-to-iterate-over-a-list-in-sophia/5236/7

**Comment by HristiyanG** [comment]
Hey @thepiwo,

Your issue has been resolved in #274 and was included in the latest release of Aeproject @2.0.1

Hrisityan
