### ISSUE TITLE
Add error handling for node and compiler 

### ISSUE THREAD

**Issue by HristiyanG** [aeternity/aepp-aeproject-js#288]

**Comment by divya088** [comment]
i am getting this error while running the AEnode
 ===== Starting Node =====
Creating myaeternity_node1_1 ... 

Creating myaeternity_proxy_1 ... 

.Creating myaeternity_proxy_1
Creating myaeternity_node1_1
Creating myaeternity_node1_1 ... done
Creating myaeternity_proxy_1 ... done

.........................................................................................===== Node was successfully stopped! =====
Cannot start AE Node!
