### ISSUE TITLE
[BUG] Operations time out with node 13.3

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#300]
**Describe the bug**
Using node 13.3 operations like `aeproject node` or `aeproject compiler` time out and show weird information, docker containers are spawned sucessfully

**To Reproduce**
1. install node 13.3
2. in exising project try to start aeproject `aeproject node` or `aeproject compiler`
3. experience long ......, then eventual incorrect messages

**Expected behavior**
aeproject node` or `aeproject compiler` finish after they spawned the node

**Screenshots**
![image](https://user-images.githubusercontent.com/6539235/70706794-f78ccb80-1cd6-11ea-976f-36a990ff566b.png)

**Aeproject information (please complete the following information):**
 - OS executed at: Linux 5.4, Docker 19.03, Node 13.3, Npm 6.13.4
 - AEproject Version 2.0.1

**Comment by thepiwo** [comment]
Doesn't seem to be related to node 13, but I don't know where else it may come from, the same project works on other machines

![image](https://user-images.githubusercontent.com/6539235/70708112-0923a280-1cda-11ea-8cb5-1fbe2e32bcbc.png)

**Comment by maptuhec** [comment]
Thanks for the issue @thepiwo, we have currently implemented some improvements in the **node** and **compiler** options, and we will investigate this issue also.

**Comment by HristiyanG** [comment]
Hey @thepiwo,

Could you confirm whether you were using docker-compose @1.25.0. We have encountered some behavioral inconsistency with the latest version of docker-compose and added support for it in the latest version of **aeproject**.
if that is the case, could you please try again and share with us if this has been resolved? 

Thank you in advance!

**Comment by thepiwo** [comment]
@HristiyanG this seems resolved with aeproject 2.1.0, the issue was the updated docker-compose version.
