### ISSUE TITLE
[BUG] Aeproject resets project aepp-sdk to old version

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#306]
**Describe the bug**
Aeproject resets project aepp-sdk to old version

**Expected behavior**
A non outdated aepp-sdk version should be used, or only upgrades should happen

**Aeproject information (please complete the following information):**
 - AEproject Version 2.1.0

**Comment by HristiyanG** [comment]
Hey Piwo,

Your issue shoukd be fixed in the latest *Aeproject* release @2.1.1
