### ISSUE TITLE
[BUG] AEProject includes old node/compiler version

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#307]
**Describe the bug**
AEProject includes old node/compiler version, an "update" resets it to old versions from manually updated ones

**Expected behavior**
Up to date node/compiler should be included and only upgrades should be applied.

**Aeproject information (please complete the following information):**
 - AEproject Version 2.1.0

**Comment by HristiyanG** [comment]
Hey @thepiwo, 
These are the tested stable versions that we could guarantee are working as intended.
This change could potentially break Aeproject.
It would be an overhaul if we change how we build our images, while we are soon expecting the core team to provide the possibility of a saenbox. As soon as this happens, we prefer to invest that time into integrating this feature. We believe this will be much more convenient for local development.

In the meantime, we'll strive to be up to date with the latest versions of the node and compiler.
Cheers! 

Hris

**Comment by thepiwo** [comment]
My problem with this is that as a developer of contracts I see the newest versions documentation online, also base-aepp and hosted infrastructure uses newer versions of everything that my tests and contract may not be compatible with perfectly.

**Comment by HristiyanG** [comment]
Hey Piwo,

Your issue should be fixed in *Aeproject* @2.1.1
