### ISSUE TITLE
Aeproject Deploy does not include the dependency file

### ISSUE THREAD

**Issue by genievot** [aeternity/aepp-aeproject-js#372]
**Describe the bug**
Aeproject current version does not include file imported in sophia contract using `include` keyword automatically upon deployment of the contracts using `aeproject deploy`. Either this or it has to be passed as a different argument in the `deploy` method and a relevant example is not to be found. 

**To Reproduce**
1. Write a contract with any dependency (That can be resolved), with `include` statement
2. After the successful compile then perform `deploy`, The compile will perform further logs and complain about this. Like the Constructor or method brought from the included Library is of unbounded type

**Expected behavior**
Either an example in the Aeproject docs that should represent how to include a separate file in the contract or if it should automatically merge with the contract then it can work with it. I used the merging technique to make it working and then move to compilation and deployment.

**Screenshots**
![image](https://user-images.githubusercontent.com/40867747/117827796-ec085000-b28e-11eb-91fb-71523ff4bab7.png)

**Aeproject information (please complete the following information):**
 - OS executed at: Ubuntu 20
 - AEproject Version: As of the current version

**Comment by mradkov** [comment]
Have you tried this with https://github.com/aeternity/aepp-aeproject-js/releases/tag/v3.0.4?

**Comment by genievot** [comment]
Yes @mradkov It works from the update
